name: CI

on:
  push:
    branches: [ feat/enable-cicd ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: cd app && yarn install
    - run: cd app && yarn test
